# Generated by Django 2.0.8 on 2018-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181007_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
