# Generated by Django 2.0.8 on 2018-10-07 18:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='default.jpg', upload_to=blog.models.blog_directory_path),
        ),
    ]
